### ISSUE TITLE
HTTP Error: 401, Request had invalid authentication credentials

### ISSUE THREAD

**Issue by lukas1** [wzieba/Firebase-Distribution-Github-Action#10]
Hi, using this github action providing a `FIREBASE_TOKEN` I'm unable to upload android apk file to Firebase App Distribution, with following error:

```
Error: failed to fetch app information. HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

Using the same `FIREBASE_TOKEN` locally, I'm able to upload the apk, I only face this problem using this workflow action. Does anybody have any idea what could be wrong? Thanks

This is my workflow file:
```
name: Distribute Debug

on:
  push:
    tags:
      - 'dev-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Debug
        run: sudo ./gradlew assembleDebug
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: some_app_id_that_is_correct
          token: ${{secrets.FIREBASE_TOKEN}}
          debug: true
          file: app/build/outputs/apk/debug/app-debug.apk
```

**Comment by jongha** [comment]
Did you tried ``appId`` with the same in local?

**Comment by lukas1** [comment]
yes. It looks like it was some issue with the firebase token. I tried creating a new one and now it works. I don't understand why previous tokens didn't work, when they worked locally, but it seems the issue is resolved. Thanks

**Comment by dheerajrijhwani** [comment]
How I can create the secrets.FIREBASE_TOKEN

**Comment by lukas1** [comment]
@dheerajrijhwani you're asking in the wrong place I suppose, that said, you can create it in your repository's settings. There's a section called `Secrets` in there

**Comment by dheerajrijhwani** [comment]
I know that. Where I can get the FIREBASE_TOKEN. I have added the appId which was available in the firebase console but I didn't find the FIREBASE_TOKEN. Can you help me on that.

**Comment by lukas1** [comment]
https://firebase.google.com/docs/cli#cli-ci-systems

On a machine with a browser, install the Firebase CLI.

Start the signin process by running the following command:

firebase login:ci

Visit the URL provided, then sign in using a Google account.

Print a new refresh token. The current CLI session will not be affected.

Store the output token in a secure but accessible way in your CI system.

Use this token when running firebase commands. You can use either of the following two options:

Store the token as the environment variable FIREBASE_TOKEN. Your system will automatically use the token.

Run all firebase commands with the --token <token> flag in your CI system.
The order of precedence for token loading is flag, environment variable, desired Firebase project.

**Comment by slice-happysingh** [comment]
@lukas1  Thanks, that worked
