### ISSUE TITLE
The action is completed successfully, even when there is an error

### ISSUE THREAD

**Issue by samuelcecilio** [wzieba/Firebase-Distribution-Github-Action#101]
Apparently the error code that happens inside the entrypoint is not forwarded to github, so this action always returns success.

This results in a false positive, because to know that something is wrong, I need to go to the workflow and click on the step that is marked as success, but at the end of the log there is an error.

https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions#setting-a-failure-exit-code-in-a-docker-container-action

<img width="499" alt="Captura de Tela 2023-02-22 às 11 01 02" src="https://user-images.githubusercontent.com/30150045/220642545-4abc7a2a-ef31-4db3-b08d-99baf1b34363.png">

**Comment by alexprudhomme** [comment]
You can add another step that checks if the upload was a success. Look at my example:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/78121423/221729075-81c783ae-75cf-4c5a-9b88-92442f0ef4de.png">

`exit 1` marks it as an error.

**Comment by moweb-Vaidehi** [comment]
Same issue happening with me

<img width="1410" alt="Screenshot 2023-03-30 at 10 35 28 AM" src="https://user-images.githubusercontent.com/127919405/228734788-31aea61c-60d9-4bf3-8273-99b0816237be.png">

**Comment by amorujao** [comment]
In my case I was still setting up the project and had an error in the inputs (empty appId) and it also succeeded despite showing an error message in the logs.

**Comment by arthurljones** [comment]
This just happened to my team - we changed a build config and that unexpectedly changed the output file.

![image](https://user-images.githubusercontent.com/145591/234072634-04a9e55d-f308-42b7-b551-77acd6330f72.png)

Another action in the script posts a comment on the PR when the build is ready, which still fired, because the upload action reported success despite an error.

**Comment by emartynov** [comment]
I assumed it should fail the job. Apparently, it doesn't. Can we fix it?

**Comment by JulienDupontDev** [comment]
Same here, got Error: failed to determine AAB info. HTTP Error: 403, Firebase App Distribution API has not been used in project but job still shows as successful, not very good for CI / CD to not have reports about a failed deployment xD
