### ISSUE TITLE
HTTP Error: 400, Request contains an invalid argument

### ISSUE THREAD

**Issue by askirk** [wzieba/Firebase-Distribution-Github-Action#102]
Hey there, I'm trying to use this action but keep getting this message without any further information, even though I set `debug:true`. Stacktrace is

```
Run wzieba/Firebase-Distribution-Github-Action@v1.5.0
  with:
    appId: ***
    serviceCredentialsFileContent: ***
  
    groups: my-group
    file: app-debug.apk
    debug: true
// some docker message commented out
i  uploading binary...

Error: failed to upload release. HTTP Error: 400, Request contains an invalid argument.
```

I'm not able to run locally with `nektos/act` to debug either, so I'm out of ideas.

**Comment by askirk** [comment]
For anyone else running into this, your `appId` does not refer to the Google cloud project app id (`my-project-1234`), but the App Id for the iOS/Android app id. Something like `1:XXXX:android:XXX`

**Comment by askirk** [comment]
For anyone else running into this, your appId does not refer to the Google cloud project app id (my-project-1234), but the App Id for the iOS/Android app id. Something like 1:XXXX:android:XXX

**Comment by princ3od** [comment]
You save me from searching the whole internet 😆

**Comment by Fiser12** [comment]
I guess that you mean the mobilesdk_app_id that you can find in the google-services.json
