### ISSUE TITLE
./Gradlew: No such file or directory

### ISSUE THREAD

**Issue by baimamboukar** [wzieba/Firebase-Distribution-Github-Action#103]
###  I have setup the workflow. It is failing at the level of building apk....
This is the error message I am getting 
`Run ./gradlew assembleRelease
/home/runner/work/_temp/9a0[8](https://github.com/inkus-org/akila/actions/runs/4708833131/jobs/8351522793#step:5:9)f3[9](https://github.com/inkus-org/akila/actions/runs/4708833131/jobs/8351522793#step:5:10)3-fe58-49f2-9d6c-042100e7e400.sh: line 1: ./gradlew: No such file or directory
Error: Process completed with exit code 127.`

How can it be fixed ?

**Comment by aman-masipeddi** [comment]
I got this issue too. However, do we have to setup anything locally for this to work?

**Comment by arowierzbowskispoton** [comment]
You need to check if the gradlew is in the root dir of the project. In my case I had a folder called `android` and in that folder gradlew was located. So I had to use `working-directory: ./android` step in my job and it worked

**Comment by wzieba** [comment]
As @arowierzbowskispoton pointed out, this looks like incorrect working directory issue. It's not related to how the action works. I'll close this issue, but please feel free to ask any questions here still.
