### ISSUE TITLE
Leaving the minor and patch out of the  declaration isn't pulling latest

### ISSUE THREAD

**Issue by orbegoso** [wzieba/Firebase-Distribution-Github-Action#105]
Using `uses: wzieba/Firebase-Distribution-Github-Action@v1` uses the the version tagged [v1](https://github.com/wzieba/Firebase-Distribution-Github-Action/releases/tag/v1), which is pointing to `1.4.0`, I would expect it to point to the latest version which is `1.5.0`.

**Comment by wzieba** [comment]
Thanks @orbegoso for the report. Sorry it took so long, it slipped out of the radar.

`v1` not points to the newest release: `v1.5.1` (commit 6fbe704a8c1bbfc7f1e21d717014e6dc1dd2cc34)
