### ISSUE TITLE
Failed to add secrect CREDENTIAL_FILE_CONTENT into Github 

### ISSUE THREAD

**Issue by votheanh39** [wzieba/Firebase-Distribution-Github-Action#114]
I followed the wiki [guide](https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration) and got stuck when try adding the private JSON key into GitHub actions repository secrets via key `CREDENTIAL_FILE_CONTENT `( Step 11 in Guide 2 )

Github returns this message error 

> Failed to add secret. Secret names can only contain alphanumeric characters ([a-z], [A-Z], [0-9]) or underscores (_). Spaces are not allowed. Must start with a letter ([a-z], [A-Z]) or underscores (_).

My JSON file have format like this

```
{
  "type": "service_account",
  "project_id": "XXXXX-395415",
  "private_key_id": "XXXXX",
  "private_key": "-----BEGIN PRIVATE KEY--XXXX--END PRIVATE KEY-----\n",
  "client_email": "XXXXX",
  "client_id": "XXXXX",
  "auth_uri": "XXXXX",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "XXXXX",
  "universe_domain": "googleapis.com"
}
```

**Comment by wzieba** [comment]
What's the name of the secret you're trying to add? Did you make sure that there's no e.g. space at the end?

**Comment by votheanh39** [comment]
Hi, I tried to add private JSON content from account service into secrect CREDENTIAL_FILE_CONTENT in Github actions.
It seems to be my machine issue since somehow when I paste the content into value input box, the content is refomatted and it causes the error above. I tried on other machine and it works fine
