### ISSUE TITLE
Run wzieba/Firebase-Distribution-Github-Action@v1 takes a lot of time

### ISSUE THREAD

**Issue by AliAzaz** [wzieba/Firebase-Distribution-Github-Action#115]
I have experienced this issue: Build wzieba/Firebase-Distribution-Github-Action@v1 takes much more time than the apk building. It takes more than 3min every time when I run my workflow. Even the other available firebase-distribution actions don't take a lot of time.

![image](https://github.com/wzieba/Firebase-Distribution-Github-Action/assets/12116478/27d5522a-fca1-45f0-a40b-038a7e26f859)

**Comment by vlazdra** [comment]
Hi @AliAzaz my PR would improve the speed #107 
We just need to wait for the creator to merge it. 🤷
