### ISSUE TITLE
where do I find FIREBASE_TOKEN?

### ISSUE THREAD

**Issue by denisvieira05** [wzieba/Firebase-Distribution-Github-Action#12]
I try many tokens but not got distribute my apk with success 

Error on  upload artifact to Firebase App Distribution Step : 
`
Error: failed to fetch app information. HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`

**Comment by wzieba** [comment]
You've to generate token on your local machine with `firebase login:ci`. More details [here](https://firebase.google.com/docs/cli#cli-ci-systems). More details here https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/10#issuecomment-608564730

**Comment by denisvieira05** [comment]
yes @wzieba , thank you !
