### ISSUE TITLE
Error: Container action is only supported on Linux for windows OS

### ISSUE THREAD

**Issue by passmanagerapp** [wzieba/Firebase-Distribution-Github-Action#120]
`name: Android CI
on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: oracle
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app
          path: app/build/outputs/apk/release/bubi_*.apk
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.6.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: app/build/outputs/apk/release/bubi_*.apk`

for this yml code, I get this error message  **Error: Container action is only supported on Linux**

**Comment by wzieba** [comment]
This action is Docker container action, and as today, it's not possible to run it on different machines than Linux ([source](https://docs.github.com/en/actions/creating-actions/about-custom-actions#docker-container-actions)).

If you can't run build on Linux host, you can always create a new Linux-based job, pass build artifacts from any other job, and use this action to send them to Firebase App Distribution. More context: https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/24#issuecomment-769731085
