### ISSUE TITLE
Error: Docker build failed with exit code 1

### ISSUE THREAD

**Issue by m-veselov** [wzieba/Firebase-Distribution-Github-Action#122]
Building this action steps finishes with an error:
Error: Docker build failed with exit code 1

**Comment by wzieba** [comment]
I just run [the test suite](https://github.com/wzieba/Firebase-Distribution-Github-Action/actions/runs/6847020891/job/18614547280) and haven't found issues. Which version of the action do you use? What's the output of the error?

**Comment by m-veselov** [comment]
> I just run [the test suite](https://github.com/wzieba/Firebase-Distribution-Github-Action/actions/runs/6847020891/job/18614547280) and haven't found issues. Which version of the action do you use? What's the output of the error?

Sorry, accidently used the ancient version. With the new one works fine! Thanks
