### ISSUE TITLE
Failed to upload the multiple apk's

### ISSUE THREAD

**Issue by Jatin9098** [wzieba/Firebase-Distribution-Github-Action#132]
- name: Upload artifacts to Firebase App Distribution
  uses: wzieba/Firebase-Distribution-Github-Action@v1
  with:
    debug: true
    appId: ${{secrets.APP_ID}}
    serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
    groups: test
    file: |
      A.apk
      B.apk
      C.apk
      
 Is there any way to upload the above 3 APK's to the Firebase
 
 Getting below error:-
 Error: Unsupported file format, should be .ipa, .apk or .aab

**Comment by wzieba** [comment]
Unfortunately, I don't see [Firebase CLI](https://firebase.google.com/docs/app-distribution/android/distribute-cli) allowing such an option, so it's likely not possible. You can always call the action 3 times, each time for a separate file.
