### ISSUE TITLE
Failed to upload release

### ISSUE THREAD

**Issue by GnuaAruht** [wzieba/Firebase-Distribution-Github-Action#136]
I followed the steps from the documentation. When the workflow is run, I got that error.

`Error: failed to upload release. HTTP Error: 400, Request contains an invalid argument.`

Here is the content of my workflow file.
`
name: Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      release_note:
        type: string
        required: true
        description: 'Release note description'
        default: "Release app to firebase"

jobs:
    run_test:
      name: Build and distribution app
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Execute gradle command - assembleRelease
          run: ./gradlew assembleRelease

        - name: upload artifact to Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{ secrets.FIREBASE_APP_ID }}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            groups: testers
            file: app/build/outputs/apk/release/app-release-unsigned.apk
            releaseNotes: ${{ inputs.release_note }}
`

**Comment by NGOYJ001** [comment]
Hwy have you been able to resolve this?

**Comment by umepy** [comment]
I got same error.

**Comment by juckrit** [comment]
I think you use wrong secrets.FIREBASE_APP_ID.

**Comment by umepy** [comment]
@juckrit 
Thanks! I misunderstood the project id as the appId.
After I changed it, it worked fine.
