### ISSUE TITLE
Sample documentation is not accurate

### ISSUE THREAD

**Issue by igorbiscanin** [wzieba/Firebase-Distribution-Github-Action#17]
I tried to use this line for the readme sample example but its failing with:

Download action repository 'wzieba/Firebase-Distribution-Github-Action@v1'
##[error]An action could not be found at the URI 'https://api.github.com/repos/wzieba/Firebase-Distribution-Github-Action/tarball/v1'

How can a latest version be used without the need for updating it with every change? Or I need to specify v1.2.2 if I want too use the latest version?

**Comment by wzieba** [comment]
@igorbiscanin I've added `v1` tag which will point to newest, `v1` major version with all hotfixes. You don't need to specify `v1.2.2` anymore.

Sorry for inconvenience, now `README.md` is correct.

**Comment by igorbiscanin** [comment]
Thanks. 👍
