### ISSUE TITLE
Github failed

### ISSUE THREAD

**Issue by juliend20** [wzieba/Firebase-Distribution-Github-Action#20]
Hi, I got an error (see the log below) on Github. 

` /usr/bin/docker build -t 8118cb:d22552a5691a4904a568a3d10045e432 -f "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1/Dockerfile" "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1"
  Sending build context to Docker daemon  11.78kB
  
  Step 1/6 : FROM node:12.10.0-alpine
  12.10.0-alpine: Pulling from library/node
  e7c96db7181b: Pulling fs layer
  95b3c812425e: Pulling fs layer
  778b81d0468f: Pulling fs layer
  28549a15ba3e: Pulling fs layer
  28549a15ba3e: Waiting
  778b81d0468f: Verifying Checksum
  778b81d0468f: Download complete
  e7c96db7181b: Download complete
  28549a15ba3e: Verifying Checksum
  28549a15ba3e: Download complete
  95b3c812425e: Verifying Checksum
  95b3c812425e: Download complete
  e7c96db7181b: Pull complete
  95b3c812425e: Pull complete
  778b81d0468f: Pull complete
  28549a15ba3e: Pull complete
  Digest: sha256:744b156ec2dca0ad8291f80f9093273d45eb85378b6290b2fbbada861cc3ed01
  Status: Downloaded newer image for node:12.10.0-alpine
   ---> ef7d474eab14
  Step 2/6 : WORKDIR /app
   ---> Running in d67a0263fb27
  Removing intermediate container d67a0263fb27
   ---> cc6721229e44
  Step 3/6 : COPY . /app
   ---> cbac1c1ba7ed
  Step 4/6 : RUN npm install -g firebase-tools     && apk update     && apk add git
   ---> Running in d3662b3305c2

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/firebase-tools/node_modules/chokidar/node_modules/fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
  
  npm ERR! code E404
  npm ERR! 404 Not Found - GET https://registry.npmjs.org/@szmarczak%2fhttp-timer - Not found
  npm ERR! 404 
  npm ERR! 404  '@szmarczak/http-timer@^1.1.2' is not in the npm registry.
  npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
  npm ERR! 404 It was specified as a dependency of 'got'
  npm ERR! 404 
  npm ERR! 404 Note that you can also install from a
  npm ERR! 404 tarball, folder, http url, or git url.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2020-08-06T10_35_20_686Z-debug.log
  The command '/bin/sh -c npm install -g firebase-tools     && apk update     && apk add git' returned a non-zero code: 1`

**Comment by wzieba** [comment]
Thanks for reporting this! I see other users/actions have exactly the same problem. https://github.com/szmarczak/http-timer/issues/22 

I'll try to find some fix for that

**Comment by wzieba** [comment]
@juliend20 this should be already fixed, I've verified it with this test run: https://github.com/wzieba/Firebase-Distribution-Github-Action/runs/953703765?check_suite_focus=true

I'm closing this issue, if it still doesn't work for you, please re-open it.

**Comment by juliend20** [comment]
@wzieba Effectively It's npm problem. Thank you for your answer and your great job. 🥇
