### ISSUE TITLE
[Feature request]more specific error log

### ISSUE THREAD

**Issue by shinriyo** [wzieba/Firebase-Distribution-Github-Action#25]
`Unknown Error` can't show the error.

```
Run wzieba/Firebase-Distribution-Github-Action@v1
  with:
    appId: fuga
    token: hoge
    groups: testers
    file: app.ipa
    debug: false
/usr/bin/docker run --name bar --label hoge --workdir /github/workspace --rm -e INPUT_APPID -e INPUT_TOKEN -e INPUT_GROUPS -e INPUT_FILE -e INPUT_RELEASENOTES -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/andu/andu":"/github/workspace" bar:hoge
i  getting app details...
i  uploading distribution...

Error: failed to upload distribution. HTTP Error: 400, Unknown Error
```

**Comment by wzieba** [comment]
This is an error code and message returned by Firebase CLI client. If you need more logs, please use `debug` flag [which is supported by this actions](https://github.com/wzieba/Firebase-Distribution-Github-Action#debug)

**Comment by shinriyo** [comment]
@wzieba Thank you.
Like this? or `debug:"true"` or `debug:'true'`?

```
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app/build/outputs/apk/release/app-release-unsigned.apk
        debug:true
```

**Comment by wzieba** [comment]
@shinriyo no problem, I don't think you have to add `'` or `"`, just use it as you did in your snippet or in this sample: https://github.com/wzieba/Firebase-Distribution-Github-Action/blob/master/.github/workflows/main.yml#L34

**Comment by shinriyo** [comment]
Thank you.
log said it. however, I uploaded ipa not apk..
```
APK is not zip aligned. (Code: APK_NOT_ZIP_ALIGNED)
```

**Comment by wzieba** [comment]
The logs produced by action are not prepared by myself but rather by Firebase CLI. I think uploading `.ipa` files should work fine, the same as uploading `.apk` files but for safety I'll add test case for `.ipa` files only: #26 .

Said this, I'll try to help you with your issue: could you please paste here the fragment of your workflow where you declare using `Firebase-Distribution-Github-Action` with its inputs?

**Comment by shinriyo** [comment]
@wzieba I'm sorry. My target is `.ipa` but I might use Android's `secrets.FIREBASE_APP_ID`.
