### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by robertoestivill** [wzieba/Firebase-Distribution-Github-Action#27]
I'm getting the following warnings on the Github actions logs.

![Screenshot 2020-09-03 at 10 44 08](https://user-images.githubusercontent.com/3728545/92092474-6ca6b080-edd2-11ea-9e29-bc449740da21.png)

Not sure what needs to be done in order to stop using deprecated libraries, but it would be nice.
Maybe a Firebase tools upgrade?

**Comment by mateuszkwiecinski** [comment]
Blocked by: https://github.com/firebase/firebase-tools/issues/2215
According to the first comment there the firebase tools team is working on removing the dependency. There is nothing that can be done on the Action side.

**Comment by wzieba** [comment]
As this is [firebase/firebase-tools](https://github.com/firebase/firebase-tools) responsibility, I close this issue. There's nothing we can do here.
