### ISSUE TITLE
releaseNotesFile seems not available

### ISSUE THREAD

**Issue by bitgandtter** [wzieba/Firebase-Distribution-Github-Action#28]
##[warning]Unexpected input(s) 'releaseNotesFile', valid inputs are ['entryPoint', 'args', 'appId', 'token', 'file', 'groups', 'releaseNotes', 'debug']

**Comment by wzieba** [comment]
It seems that everything works fine, at least on our test run: https://github.com/wzieba/Firebase-Distribution-Github-Action/runs/1095883828?check_suite_focus=true#step:5:37

Which version of `Firebase-Distribution-Github-Action` do you use?

**Comment by bitgandtter** [comment]
Im using v1

`
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: internal
          releaseNotesFile: ReleaseNotes.txt
          file: build/app/outputs/apk/release/app-release.apk
`

**Comment by wzieba** [comment]
Ok, the `v1` tag was pointing to the old commit. `releaseNotesFile` should be available now.

**Comment by bitgandtter** [comment]
Excellent it works now, thanks
