### ISSUE TITLE
how can I cache the setup [Question]

### ISSUE THREAD

**Issue by fayaz07** [wzieba/Firebase-Distribution-Github-Action#32]
As fetching the dependencies every-time is bit costly, I would like to cache the setup. Please let me know how can I do that.
Thanks

**Comment by wzieba** [comment]
hi @fayaz07 thanks for this question. I'm not yet sure how it can be approached. One idea might be to put Docker image in [Docker Hub](https://hub.docker.com/) and then maybe cache it with [this action](https://github.com/marketplace/actions/build-docker-images-using-cache) but this needs changes on the action side. I don't have any ideas on how the user of the action could cache it now.

It's a definitely good idea to check how we can improve action build speed though. Recently I don't have much time so any help would be warmly welcomed 👍

**Comment by fayaz07** [comment]
Hi @wzieba I am not aware of docker and all, maybe if I get through those concepts I will raise a PR

**Comment by pinkasey** [comment]
I hope you don't mind me barging in (I'm not a maintainer), but I think I can contribute to this thread -

@fayaz07 
Do you mean you want to cache the dependencies for the **build** step, when you build your apk/aab?
If so -
that's a different step, and a different github-action. I don't think you should be asking here.

Here's a screenshot from one of my builds:
![image](https://user-images.githubusercontent.com/1780369/117269770-3e95d680-ae61-11eb-952e-96d1f377ba8c.png)
The last step is the step that run this action (`Firebase-Distribution-Github-Action`), and it only takes 13 seconds.
 I think you're interested in improving the previous step - building the apk - which takes almost 5 minutes.
The first step in my screenshot is getting the flutter dependencies - takes 28 seconds. And yes - I think it can be cached.

Github [supports caching dependencies](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action) - maybe that's what you're looking for.
I haven't tried it myself yet, but it sounds easy enough.

**Comment by fayaz07** [comment]
@pinkasey 
why would someone in this universe cache build step 😆😆
I was asking about `flutter` setup

**Comment by pinkasey** [comment]
Then I suggest you try [the link](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action) that I provided 🙂 

And I think this ticket can be closed -
this action has nothing to do with flutter, it publishes apk/aab, it doesn't build them.

**Comment by fayaz07** [comment]
Sure

**Comment by wzieba** [comment]
Thank you for discussion folks. If we speak hear about dependencies of the action itself (more specifically: a docker image), I don't know any way to cache it.
