### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by davidmcraejr** [wzieba/Firebase-Distribution-Github-Action#33]
Using this config in my deploy action:

```
      - name: Deploy to firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_STAGING_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: app/build/outputs/apk/staging/app-staging.apk
          debug: true
```

I get the below error that I can't quite figure out:

[2020-10-16T21:42:24.001Z] Error: EISDIR: illegal operation on a directory, read
Error: An unexpected error has occurred.

Any ideas would be helpful, thanks!

**Comment by davidmcraejr** [comment]
Figured out my issue, when I set the directory for the APK to be downloaded it was creating a directory with the apk in it `app-staging.apk/app-staging.apk`, fixed that and all is working correctly.  Thanks!

**Comment by wzieba** [comment]
Thank you @davidmcraejr for sharing this! Your issue with creating a directory might be helpful for anyone who came across a similar case. Sorry, I didn't help you here, I couldn't pay much attention to this project lately.
