### ISSUE TITLE
App versions from git tags

### ISSUE THREAD

**Issue by Arna-Maity** [wzieba/Firebase-Distribution-Github-Action#38]
Is there any way we can set the app versions (in firebase console) using git tags?

**Comment by wzieba** [comment]
If it's Android, I'd suggest some Gradle plugin like this: https://github.com/gladed/gradle-android-git-version If iOS - I don't know anything but I'm pretty sure there are some Cocoapods or something like this for git-based versioning :)

As this Github Action is not meant to be responsible for artifact versioning, I'll close this issue.

**Comment by Arna-Maity** [comment]
Ok. Thanks for the prompt reply @wzieba . I will go through the above mentioned Gradle plugin.
