### ISSUE TITLE
Requested access to the resource is denied

### ISSUE THREAD

**Issue by Zarkend** [wzieba/Firebase-Distribution-Github-Action#39]
Hi, does I'm receiving this error since a while, have anyone experienced it before?

```
Unable to find image '5588e4:2ad8139ecb904f3682b4dfd9867530ee' locally
docker: Error response from daemon: pull access denied for 5588e4, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
``````

![image](https://user-images.githubusercontent.com/22328325/115012127-bb134600-9eaf-11eb-8366-d62248d02d86.png)

**Comment by wzieba** [comment]
Thanks for the report @Zarkend. I've just run tests and it seem it works fine here: https://github.com/wzieba/Firebase-Distribution-Github-Action/runs/2361455055?check_suite_focus=true

I'm not sure what can be an issue for `docker: Error response from daemon: pull access denied for 5588e4`. The test linked above doesn't use cache and it downloads the same image as you do. Please see this line: https://github.com/wzieba/Firebase-Distribution-Github-Action/runs/2361455055?check_suite_focus=true#step:4:10

I'm wondering if it can be Github Actions itself issue? I don't have any ideas for now.

**Comment by Zarkend** [comment]
Thanks for the fast response! The only thing I see different is the Building docker image step (https://github.com/wzieba/Firebase-Distribution-Github-Action/runs/2361455055?check_suite_focus=true#step:4:8)

It's strange since I'm using the same github runner (ubuntu-latest), will keep investigating, thanks for your time!

**Comment by wzieba** [comment]
Hi @Zarkend 👋 I hope you fixed this error. If not, please feel free to re-open the issue, thanks!
