### ISSUE TITLE
Dynamic release notes

### ISSUE THREAD

**Issue by jogcaetano13** [wzieba/Firebase-Distribution-Github-Action#40]
There is a way that I can add the release notes dynamically from Android gradle?

**Comment by wzieba** [comment]
Hi, I'm not sure if I understand "release notes from Android gradle" - could you please clarify?

If you've got some Gradle task which output are release notes, you can e.g. execute this task, save output in environmental variable and then use it in the action's `releaseNotes` parameter.

**Comment by jogcaetano13** [comment]
Hi. Thanks for the response. That's it, I need to save output in environmental variable. Thank you.

**Comment by thanhnt-mdev** [comment]
Hi,
When I remove releaseNotes param, it will not generate even last commit as the docs said

**Comment by wzieba** [comment]
Hi @thanhnt-mdev , that sounds like a bug. Could you please create a new issue and add your workflow configuration so I can have a better idea on how to help? I'll be closing this issue as the original question has been answered. Thank you!
