### ISSUE TITLE
Support for App Bundle upload

### ISSUE THREAD

**Issue by tejas-rapido** [wzieba/Firebase-Distribution-Github-Action#45]
Now that Firebase App Distribution has started accepting App bundles, do we have a provision to upload the AAB files instead of APK files?

More details here - https://firebase.googleblog.com/2021/05/app-distribution-adds-support-to-android-app-bundles.html

**Comment by amitav13** [comment]
Can confirm, this also works with AAB as-is.

**Comment by tejas-rapido** [comment]
Thanks @amitav13 for the confirmation and the PR :)
