### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by IgorGanapolsky** [wzieba/Firebase-Distribution-Github-Action#47]
Hello, I have followed your instructions in the README file.  I have the following github action:
`deploy-firebase:
    # 1
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      # 2
      - uses: actions/download-artifact@v2
        with:
          name: app-release.aab
      # 3
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${secrets.FIREBASE_APP_ID }}
          token: ${{secrets.FIREBASE_TOKEN }}
          groups: QA
          file: app/build/outputs/bundle/release/app-release.aab
`

However, I get an error:
> Run wzieba/Firebase-Distribution-Github-Action@v1
/usr/bin/docker run --name bec5f756fee773e98473db538e4384401ae5a_82bc48 --label 3bec5f --workdir /github/workspace --rm -e INPUT_APPID -e INPUT_TOKEN -e INPUT_GROUPS -e INPUT_FILE -e INPUT_SERVICECREDENTIALSFILE -e INPUT_RELEASENOTES -e INPUT_RELEASENOTESFILE -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/partnersso-android/partnersso-android":"/github/workspace" 3bec5f:756fee773e98473db538e4384401ae5a
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error: failed to fetch app information. HTTP Error: 400, Request contains an invalid argument.

**Comment by murilogok** [comment]
` ${secrets.FIREBASE_APP_ID }}`

Check your appId secret, is missing one more "{" as I can see. Anyway you should check your firebase token if was generated by firebase CI login.

**Comment by IgorGanapolsky** [comment]
I changed that.  Still getting the error:
> Unable to resolve action `wzieba/Firebase-Distribution-Github-Action@v2`, unable to find version `v2`

**Comment by murilogok** [comment]
> I changed that. Still getting the error:
> 
> > Unable to resolve action `wzieba/Firebase-Distribution-Github-Action@v2`, unable to find version `v2`

Im so sorry, I was talking about **@v1.2.1** version, I have edited my comment with the correct version. Btw this actions is working perfect on my pipe, please check your implementation!

**Comment by murilogok** [comment]
Try to check if your appId is correct. The following image is an example where appId is located

<img width="938" alt="Captura de Tela 2021-08-09 às 14 29 10" src="https://user-images.githubusercontent.com/83665217/128748669-28400342-acbc-4dda-a503-98ebd0aac4fc.png">

**Comment by IgorGanapolsky** [comment]
I tried everything.  Still getting the error:
> fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error: failed to fetch app information. HTTP Error: 400, Request contains an invalid argument.

**Comment by IgorGanapolsky** [comment]
Here is what the full output looks like:
<img width="1409" alt="Screen Shot 2021-08-09 at 2 37 39 PM" src="https://user-images.githubusercontent.com/201209/128756817-b4448ab7-3454-43ec-9e7a-29980dc8b58b.png">

**Comment by wzieba** [comment]
I think it's because action [will try to get release notes from last commit's message](https://github.com/wzieba/Firebase-Distribution-Github-Action#releasenotes), if you don't specify any release notes. 

This job is probably in container without cloned repository, is it?

**Comment by IgorGanapolsky** [comment]
Yes that's correct.
