### ISSUE TITLE
Build failed when i use target sdk 31

### ISSUE THREAD

**Issue by syntaxxxxx** [wzieba/Firebase-Distribution-Github-Action#54]

**Comment by syntaxxxxx** [comment]
name: Build & upload to Firebase App Distribution 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build stg 
      run: ./gradlew --stacktrace assembleStgDebug && find -type d -print
    - name: upload apk to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: altea-team
        file: app/build/outputs/apk/stg/debug/app-stg-universal-debug.apk

**Comment by syntaxxxxx** [comment]
i got error in github actions Execution failed for task ':app:kaptStgDebugKotlin
anyone can help me fix this issue?
thank you

**Comment by mateuszkwiecinski** [comment]
Failure during Gradle task execution isn't caused by _Firebase App Distribution_ action, clearly it happens before the action gets invoked. Please do ask on stackoverflow or a dedicated slack/forum/study group (don't forget to share full error stacktrace there). Good luck!

**Comment by syntaxxxxx** [comment]
@mateuszkwiecinski thank you mateuszkwiecinski !
