### ISSUE TITLE
Release version in Firebase app distribution stays at 1.0.0 (1)

### ISSUE THREAD

**Issue by thomasreisinger** [wzieba/Firebase-Distribution-Github-Action#57]
After several GitHubAction runs the app release version stay at 1.0.0 (1) in firebase app distribution. There is no parameter for the version such as tag: v1.0.${{ github.run_number }}

**Comment by wzieba** [comment]
Thanks for the idea but Firebase App Distribution doesn't allow to specify a version of the app during the upload. Those are available options we can use:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/5845095/161438827-3776b48c-637b-40cd-8342-270c2d6a8c16.png">

To specify a version of the Android app, see `build.gradle` of your Gradle module which applies the `com.android.application` plugin, and look for `versionName` and `versionCode` fields.

I'm closing this issue as there's nothing we can really in the action code regarding this.
