### ISSUE TITLE
Error: failed to upload release. HTTP Error: 401

### ISSUE THREAD

**Issue by dearpranay** [wzieba/Firebase-Distribution-Github-Action#59]
For `FIREBASE_TOKEN` and `FIREBASE_APP_ID`, I have logged in to my android studio terminal and generated token via google login and get app id from firebase console. Same that I have added in repo -> security and -> secrets with the same variable name metioned in workflow file, but on app build success it give me below error:

```
Error: failed to upload release. HTTP Error: 401, {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
```
Thanks, Any help would be appreciated.

**Comment by amitav13** [comment]
Same here, I had this working a couple of weeks ago but I'm getting this error as well. 

`Error: failed to determine AAB info. HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`

**Comment by NizarETH** [comment]
me too
`"message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid `

**Comment by wzieba** [comment]
Thanks for the reports.

I just run test scenarios and the action is working correctly: https://github.com/wzieba/Firebase-Distribution-Github-Action/runs/5806759755?check_suite_focus=true

Please make sure you generate a valid token as explained here https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/10#issuecomment-608564730.

Please remember that every token has its validity period, so maybe you need to re-generate a new one if it was working for you before.

I'm closing this issue as there's nothing I can do in the action code itself to resolve the described problem.
