### ISSUE TITLE
Error: failed to upload release. HTTP Error: 403

### ISSUE THREAD

**Issue by auliakbarh** [wzieba/Firebase-Distribution-Github-Action#60]
```
Error: failed to upload release. HTTP Error: 403, ***
  "error": ***
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  ***
***
```

What permission should be granted to solve this error? Any help would be appreciated. Thank you.

**Comment by auliakbarh** [comment]
apparently, I just need permission as iam.serviceAccounts.ActAs

**Comment by YvesKalume** [comment]
Hi @auliakbarh how did you fix this issue ?

**Comment by wzieba** [comment]
If you have issues with the service account approach, see the detailed instructions available here: https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration

**Comment by AL1080899** [comment]
> If you have issues with the service account approach, see the detailed instructions available here: https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration

It's now working, thank you very much ! 
I had a key with the wrong role ...
