### ISSUE TITLE
Docker image is broken

### ISSUE THREAD

**Issue by ericchenwws** [wzieba/Firebase-Distribution-Github-Action#63]
Build container for action use: '/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1.3.2/Dockerfile'.
  /usr/bin/docker build -t 08450d:97077[2](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:2)709332452ba43e63d376f51476 -f "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1.3.2/Dockerfile" "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1.3.2"
  Sending build context to Docker daemon  13.82kB
  
  Step 1/6 : FROM node:14.4.0-alpine3.12
  14.4.0-alpine3.12: Pulling from library/node
  df20fa9351a1: Pulling fs layer
  fc9f7c259fca: Pulling fs layer
  8c427793ab10: Pulling fs layer
  f38bde24d0c3: Pulling fs layer
  f38bde24d0c3: Waiting
  8c427793ab10: Verifying Checksum
  8c427793ab10: Download complete
  df20fa9351a1: Download complete
  f38bde24d0c3: Verifying Checksum
  f38bde24d0c3: Download complete
  df20fa9351a1: Pull complete
  fc9f7c259fca: Verifying Checksum
  fc9f7c259fca: Download complete
  fc9f7c259fca: Pull complete
  8c427793ab10: Pull complete
  f38bde24d0c3: Pull complete
  Digest: sha256:3465907b06c3ace503458622dcda723586825baf39c3d5bd956c752552cb7b80
  Status: Downloaded newer image for node:14.4.0-alpine3.12
   ---> 9736f552d33b
  Step 2/6 : WORKDIR /app
   ---> Running in a81801b444d1
  Removing intermediate container a81801b444d1
   ---> 63ed4bbb8d0f
  Step 3/6 : COPY . /app
   ---> 8a44c996c52f
  Step 4/6 : RUN yarn global add firebase-tools     && apk update     && apk add git
   ---> Running in 425025afb396
  yarn global v1.22.4
  [1/4] Resolving packages...
  warning firebase-tools > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  warning firebase-tools > tweetsodium@0.0.5: tweetsodium is deprecated and unmaintained. Please consider using libsodium.js, maintained by the same author as libsodium: https://github.com/jedisct1/libsodium.js
  warning firebase-tools > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  warning firebase-tools > request > har-validator@5.1.5: this library is no longer supported
  [2/4] Fetching packages...
  error marked-terminal@5.1.1: The engine "node" is incompatible with this module. Expected version ">=14.13.1 || >=16.0.0". Got "14.4.0"
  error Found incompatible module.
  info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
  The command '/bin/sh -c yarn global add firebase-tools     && apk update     && apk add git' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 8.338 seconds before retry.
  /usr/bin/docker build -t 08450d:970772709332452ba43e63d376f51476 -f "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1.3.2/Dockerfile" "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1.3.2"
  Sending build context to Docker daemon  1[3](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:3).82kB
  
  Step 1/6 : FROM node:14.4.0-alpine3.12
   ---> 9736f552d33b
  Step 2/6 : WORKDIR /app
   ---> Using cache
   ---> 63ed4bbb8d0f
  Step 3/6 : COPY . /app
   ---> Using cache
   ---> 8a44c996c52f
  Step 4/6 : RUN yarn global add firebase-tools     && apk update     && apk add git
   ---> Running in 6fd60a44e2f0
  yarn global v1.22.4
  [1/4] Resolving packages...
  warning firebase-tools > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  warning firebase-tools > tweetsodium@0.0.5: tweetsodium is deprecated and unmaintained. Please consider using libsodium.js, maintained by the same author as libsodium: https://github.com/jedisct1/libsodium.js
  warning firebase-tools > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  warning firebase-tools > request > har-validator@5.1.5: this library is no longer supported
  [2/4] Fetching packages...
  error marked-terminal@5.1.1: The engine "node" is incompatible with this module. Expected version ">=14.13.1 || >=16.0.0". Got "14.4.0"
  error Found incompatible module.
  info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
  The command '/bin/sh -c yarn global add firebase-tools     && apk update     && apk add git' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 2.261 seconds before retry.
  /usr/bin/docker build -t 08450d:970772709332452ba43e63d376f51476 -f "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1.3.2/Dockerfile" "/home/runner/work/_actions/wzieba/Firebase-Distribution-Github-Action/v1.3.2"
  Sending build context to Docker daemon  13.82kB
  
  Step 1/6 : FROM node:1[4](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:4).4.0-alpine3.12
   ---> 9736f[5](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:5)52d33b
  Step 2/[6](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:6) : WORKDIR /app
   ---> Using cache
   ---> 63ed4bbb8d0f
  Step 3/6 : COPY . /app
   ---> Using cache
   ---> 8a44c996c52f
  Step 4/6 : RUN yarn global add firebase-tools     && apk update     && apk add git
   ---> Running in 55863dcd2b26
  yarn global v1.22.4
  [1/4] Resolving packages...
  warning firebase-tools > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  warning firebase-tools > tweetsodium@0.0.5: tweetsodium is deprecated and unmaintained. Please consider using libsodium.js, maintained by the same author as libsodium: https://github.com/jedisct1/libsodium.js
  warning firebase-tools > request > uuid@3.4.0: Please upgrade  to version [7](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:7) or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v[8](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:8).dev/blog/math-random for details.
  warning firebase-tools > request > har-validator@5.1.5: this library is no longer supported
  [2/4] Fetching packages...
  error marked-terminal@5.1.1: The engine "node" is incompatible with this module. Expected version ">=14.[13](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:13).1 || >=16.0.0". Got "[14](https://github.com/woolworthslimited/wx-metro-sixty-ios/runs/6500862535?check_suite_focus=true#step:2:14).4.0"
  error Found incompatible module.
  info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
  The command '/bin/sh -c yarn global add firebase-tools     && apk update     && apk add git' returned a non-zero code: 1
Error: Docker build failed with exit code 1

**Comment by zhandoszhakanov** [comment]
Having the same issue, any ideas how to resolve it?

**Comment by ericchenwws** [comment]
> 

Not really. Have to wait until the Docker file fixed I guess.

**Comment by nhan1906duong** [comment]
I face the same

**Comment by wzieba** [comment]
hi, I've prepared a new [release](https://github.com/wzieba/Firebase-Distribution-Github-Action/releases/tag/v1.3.3) with the fix: `v1.3.3` (or `v1`).

Does it work for you?

**Comment by ericchenwws** [comment]
> hi, I've prepared a new [release](https://github.com/wzieba/Firebase-Distribution-Github-Action/releases/tag/v1.3.3) with the fix: `v1.3.3` (or `v1`).
> 
> Does it work for you?

Yes, you've fixed it! Thanks for the swift response, you saved my day!

**Comment by wzieba** [comment]
Kudos to @GMetaxakis for preparing the PR with Docker image bump 🙌 !
