### ISSUE TITLE
Version compatibility issue.

### ISSUE THREAD

**Issue by subinsuresh** [wzieba/Firebase-Distribution-Github-Action#69]
How can I get rid from error "Firebase CLI v11.0.1 is incompatible with Node.js v12.10.0 Please upgrade Node.js to version >= 14.18.0"

name: Firebase App Distribution
uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
with:
appId: ${{secrets.FIREBASE_APP_ID}}
token: ${{secrets.FIREBASE_TOKEN}}
groups: pre-sprint
file: build/app/outputs/apk/release/app-release.apk

**Comment by JasurbekA** [comment]
@wzieba yes it worked for me but release notes are missing when I receive a build from App tester
Could you please check if we need to explicitly specify? If yes then please update the Readme file

**Comment by subinsuresh** [comment]
@wzieba  Thanks. Its worked ;-)
