### ISSUE TITLE
fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by Merrick17** [wzieba/Firebase-Distribution-Github-Action#74]
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:
	git config --global --add safe.directory /github/workspace
Error: Failed to authenticate, have you run firebase login?

**Comment by wzieba** [comment]
What's the problem you're dealing with? The first three lines are free to ignore. The fourth one points to an authentication problem. Have you provided `token`?

**Comment by davidmigloz** [comment]
It is caused by https://github.blog/2022-04-12-git-security-vulnerability-announced/

You can find more info in this ticket https://github.com/actions/checkout/issues/760

I've sent you a PR with the fix (https://github.com/wzieba/Firebase-Distribution-Github-Action/pull/76)

**Comment by wzieba** [comment]
Thanks, @davidmigloz for your contribution.

Your PR fixes a warning that @Merrick17 is presenting in the first 3 lines but I think it won't fix the "Error: Failed to authenticate, have you run firebase login?".

But I think your PR did fix another issue which is #67 🙂.

I'm okay with closing this issue as well though. @Merrick17 feel free to reopen it (or another one) if you need any help.
