### ISSUE TITLE
[hepl wanted] Mac hosted

### ISSUE THREAD

**Issue by mvn-tony-hn** [wzieba/Firebase-Distribution-Github-Action#80]
I tried to upload & download my ipa file (around more than 20mb) by using upload&download-artifact action as [this suggesstion](https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/24#issuecomment-769731085). 
But when upload to firebase distribution I always get the error below:
`Error: failed to upload release. There's been an error processing your app. Ensure you are uploading a valid IPA and try again. If this problem continues, contact Firebase support.`
Do you have any suggestions for this case?

<img width="947" alt="Screen Shot 2022-07-18 at 14 17 00" src="https://user-images.githubusercontent.com/1393826/179461594-b8bdb055-322e-4ae0-8e3c-e05cdf14b6bc.png">

**Comment by wzieba** [comment]
This was likely an issue with IPA file or maybe mismatched name after passing artifacts from one job to another. This GitHub Action can't help in either of these cases - I'll close this issue as obsolete.
