### ISSUE TITLE
Can we have the output data?

### ISSUE THREAD

**Issue by minhchienwikipedia** [wzieba/Firebase-Distribution-Github-Action#85]
Hi, can we have the output data like the release link, download url?
<img width="509" alt="image" src="https://user-images.githubusercontent.com/20647079/193562596-5b00c7a9-ec13-4255-a2de-39e5f4606211.png">

**Comment by ultimaterex** [comment]
We'd be interested in this output data as well, specifically the firebase console release, tester access and release binary url's.

**Comment by rebehe** [comment]
Hey folks, engineer on App Distribution here! You may already be aware of this, but I just wanted you all to know that we recently launched release links: https://firebase.google.com/docs/app-distribution/best-practices-distributing-apple-apps-to-qa-testers-with-ci-cd-fastlane#help-testers-test-correct-app-version. All the CLI tools will now print out the three links (firebase console, testing, binary download), which you can use to set GHA output variables.

**Comment by minhchienwikipedia** [comment]
@wzieba can you update this one?

**Comment by RafaRuiz** [comment]
Looking for this 👍

**Comment by dinisnunes1** [comment]
Is there any change to include those links on an output variable?

**Comment by wzieba** [comment]
hi folks 👋 sorry for keeping you wait for so long for this feature. I've recently had some time to introduce it. Before releasing it, maybe you could give some feedback if it works for you?

You should be able to run the action pointing `wzieba/Firebase-Distribution-Github-Action@8745853`. It will produce following outputs:
- `FIREBASE_CONSOLE_URI`
- `TESTING_URI`
- `BINARY_DOWNLOAD_URI`

The WIP branch is [`save_links_to_github_output`](https://github.com/wzieba/Firebase-Distribution-Github-Action/compare/save_links_to_github_output).

**Comment by morayl** [comment]
I used TESTING_URI and it worked!
This is helpful as I just wanted this feature.

**Comment by wzieba** [comment]
This feature was released in https://github.com/wzieba/Firebase-Distribution-Github-Action/releases/tag/v1.7.0
