### ISSUE TITLE
Failed to authenticate, have you run firebase login?

### ISSUE THREAD

**Issue by chornthorn** [wzieba/Firebase-Distribution-Github-Action#88]
Error: Failed to authenticate, have you run firebase login?

**Comment by executive-visit** [comment]
yes i too get the same issue , i have added the token but still getting the error

**Comment by trancongdung12** [comment]
same issue

**Comment by wzieba** [comment]
Thanks for the report, but it's not something that this action can fix. The action itself [works fine](https://github.com/wzieba/Firebase-Distribution-Github-Action/actions/runs/3591411002/jobs/6045897335).

If you have configuration issues, [this detailed guide](https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration) may be helpful.

**Comment by trancongdung12** [comment]
<img width="814" alt="Screen Shot 2022-12-01 at 16 58 02" src="https://user-images.githubusercontent.com/55046284/205023316-b006f6b9-8ec2-4ddc-b4f1-893e363fa4bc.png">
@wzieba how to resolve this issue?
