### ISSUE TITLE
Error: failed to upload release. HTTP Error: 400, Request contains an invalid argument.

### ISSUE THREAD

**Issue by Alex-Faraday** [wzieba/Firebase-Distribution-Github-Action#89]
Stop working with serviceCredentialsFileContent :(
Example:
.............
- name: build debug
        run: ./gradlew assembleDebug

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_PROJECT_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true

Result: Error: failed to upload release. HTTP Error: 400, Request contains an invalid argument.

**Comment by Alex-Faraday** [comment]
Sorry, my bad

**Comment by Alex-Faraday** [comment]
Sorry, my bad

**Comment by askirk** [comment]
> Sorry, my bad

What was your issue? I'm running into the same thing
