### ISSUE TITLE
Error: This project is not linked to a Google Play account.

### ISSUE THREAD

**Issue by cksynoverge** [wzieba/Firebase-Distribution-Github-Action#90]
- name: Firebase App Distribution
  uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
    with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        releaseNotesFile: ".github/workflows/release_notes.txt"
        file: "build/app/outputs/bundle/release/app-release.aab"
        

**What have I done already?**

- Create a Firebase Project for android
- Download that JSON and put it in the app root directory
- While pushing the code to GitHub via Actions, I am able to create Build and Release in Github but can't able to see in Firebase App Distribution.
-  I just want to release it on Firebase Distribution, not on Google Play Store. 

> Error: This project is not linked to a Google Play account. What could be the issue?

**Comment by wzieba** [comment]
Hi, thanks for the report.

> I just want to release it on Firebase Distribution, not on Google Play Store.

I understand, but this is requirement from Firebase Distribution. More info [here](https://firebase.google.com/docs/app-distribution/android/distribute-cli?authuser=0&apptype=aab#before-you-begin). There's nothing that this action can do to overcome this requirement.

If you don't want to link project to Google Play Store, consider uploading `.apk` and not `.aab` file.

**Comment by cksynoverge** [comment]
Okay, thanks for the quick update. 

Here applying your feedback but giving me an error

```
Run ./gradlew assembleRelease
  ./gradlew assembleRelease
  shell: /usr/bin/bash -e ***0***
  env:
    JAVA_HOME_12.0.2_x64: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME_12_0_2_X64: /opt/hostedtoolcache/jdk/12.0.2/x64
/home/runner/work/_temp/1229e17b-3e4f-439c-8c6f-9ef16f95fb2b.sh: line 1: ./gradlew: No such file or directory
**Error: Process completed with exit code 127.** 
```
name: Build & upload to Firebase App Distribution
'on':
  push:
    tag:
      - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: build release
        run: ./gradlew assembleRelease
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: '${{secrets.FIREBASE_APP_ID}}'
          serviceCredentialsFileContent: '${{ secrets.CREDENTIAL_FILE_CONTENT }}'
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk

**Comment by cksynoverge** [comment]
Thanks for the support it works for me.
