### ISSUE TITLE
Failed to upload release. HTTP Error: 403, The caller does not have permission

### ISSUE THREAD

**Issue by Am271** [wzieba/Firebase-Distribution-Github-Action#91]
I have set the Service Credential File and setup firebase. It works only with token

**Comment by wzieba** [comment]
Please see [the guide](https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration). The action itself [works fine](https://github.com/wzieba/Firebase-Distribution-Github-Action/actions/runs/3591411002/jobs/6045897335). If you still have issues, feel free to share more context/configuration/MRE.
