### ISSUE TITLE
Parameter name wrong in Firebase Token migration guide

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [wzieba/Firebase-Distribution-Github-Action#96]
In the [Firebase Token migration guide](https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration) the `serviceCredentialsFileContent` parameter name seems to be incorrect. There is only a `serviceCredentialsFile` parameter.

**Comment by wzieba** [comment]
What action version do you use? `serviceCredentialsFileContent` has been introduced in [`1.4.0`](https://github.com/wzieba/Firebase-Distribution-Github-Action/blob/v1.4.0/action.yml#L14).

**Comment by lukasz-kalnik-gcx** [comment]
Sorry, I just realized I was still on `1.3.5`. Thanks for the super quick answer!
