### ISSUE TITLE
Action is only supported on Linux

### ISSUE THREAD

**Issue by mikezamayias** [wzieba/Firebase-Distribution-Github-Action#97]
I cannot use this action on a self-hosted runner on my M1 machine, as I found out from the error `Container action is only supported on Linux`. With this action succeeding, it'd be cool to complete my workflow on my self-hosted runner.

**Comment by michakfromparis** [comment]
I second that. Was about to open the same issue

**Comment by wzieba** [comment]
It's a duplicate of #24 .

Docker-based actions are only supported on Linux. For now, I don't plan to rewrite this action to Javascript one. More context [here](https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/24#issuecomment-683381060).

The possible solution is presented [here](https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/24#issuecomment-769731085) although it might not be a good fit for a self-hosted runner.
